# SECRET_KEY = 'Very secret'

# OAUTH2_REFRESH_TOKEN_GENERATOR = True

SQLALCHEMY_DATABASE_URI = f'mysql+pymysql://user:demo@db/game-store'
SQLALCHEMY_TRACK_MODIFICATIONS = False
# SQLALCHEMY_ECHO = True
SQLALCHEMY_ENGINE_OPTIONS = {}
