version: "3.7"

volumes:
  dbdata:

services:
  backend:
    build:
      context: ./
    ports:
      - 5000:5000
    environment:
      FLASK_APP: "game_store:create_app()"
      PYTHONUNBUFFERED: 1
      AUTHLIB_INSECURE_TRANSPORT: 1
    depends_on:
      - db
    restart: unless-stopped

  db:
#    image: mariadb:latest
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: user
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: game-store
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: unless-stopped
