version: "3.7"

volumes:
  dbdata:

services:
  backend:
    build:
      context: ./
    ports:
      - 8080:5000
    environment:
      FLASK_APP: "game_store:create_app()"
      FLASK_ENV: development
      PYTHONUNBUFFERED: 1
    volumes:
      - ./instance:/app/instance
      - ./game_store:/app/game_store
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: user
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: game-store
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db
    restart: unless-stopped
