version: "3.7"

volumes:
  dbdata:

services:
  backend:
    build:
      context: ./
    ports:
      - 8080:5000
    environment:
      FLASK_APP: "todo:create_app()"
#      FLASK_ENV: development
      PYTHONUNBUFFERED: 1
    volumes:
      - ./instance:/app/instance
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: todo
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@db:27017/
    depends_on:
      - db
    restart: unless-stopped
