version: "3.7"

services:
  backend:
    environment:
      FLASK_ENV: development
    volumes:
      - ./instance:/app/instance
      - ./auth_server:/app/auth_server
      - ../../flask_restlib:/python_packages/flask_restlib:ro
